name-template: 'v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
commitish: 'main'
template: |
  ## Whatâ€™s Changed
  $CHANGES
categories:
  - title: 'ğŸŠ Features'
    labels:
      - 'feature'
      - 'feat'
  - title: 'ğŸ Bug Fixes'
    labels:
      - 'fix'
  - title: 'ğŸ› ï¸ Refactor'
    labels:
      - 'refactor'
      - 'style'
  - title: 'ğŸ–‹ï¸ Maintenance'
    labels:
      - 'chore'
      - 'ci'
  - title: 'ğŸ“ Docs/Test'
    labels:
      - 'docs'
      - 'test'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch